### ISSUE TITLE
NPE for non java projects (e.g. pom/module projects)

### ISSUE THREAD

**Issue by hohwille** [mojohaus/servicedocgen-maven-plugin#17]
```
Caused by: java.lang.NullPointerException
        at org.codehaus.mojo.servicedocgen.GenerateMojo.scanJavaFilesRecursive(GenerateMojo.java:191)
        at org.codehaus.mojo.servicedocgen.GenerateMojo.scanServices(GenerateMojo.java:173)
        at org.codehaus.mojo.servicedocgen.GenerateMojo.execute(GenerateMojo.java:133)
        ... 21 more
```

**Comment by hohwille** [comment]
Line 191 is:

```
for ( File file : sourceDir.listFiles() )
```

This would mean that `sourceDir` is null.
How can this happen? It is the argument `sourceFolder` from this code:

```
            File sourceFolder = new File( sourceDir );
            builder.addSourceFolder( sourceFolder );
            if ( this.serviceClassName == null )
            {
                scanJavaFilesRecursive( sourceFolder, builder, serviceClasses );
            }
```

**Comment by hohwille** [comment]
Can `File.listFiles()` return null or a `File[]` with a `null` entry?

**Comment by hohwille** [comment]
OK. `File.listFiles()` indeed returns `null` if the path does not exist. Stupid one.

**Comment by hohwille** [comment]
fixed with this commit (typo in issue number, sorry):
https://github.com/mojohaus/servicedocgen-maven-plugin/commit/bfe86535eb5b02eab94f10fefca46fdffab435af
